(()=>{
'use strict';
const M=window.FortuneModel,S=window.FortuneSpinStyle,$=id=>document.getElementById(id);
if(!M){console.error('FortuneModel missing');return;}
const st={models:[],history:[],busy:false,undo:null,heartbeat:null,started:0};
const clone=v=>M.deepClone?M.deepClone(v):JSON.parse(JSON.stringify(v));
const clamp=(v,a,b,d)=>{v=Number(v);return Number.isFinite(v)?Math.min(b,Math.max(a,v)):d;};
const slug=s=>String(s||'item').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,42)||'item';
const provider=()=>$('aiProvider')?.value||'custom';
const token=()=>$('aiToken')?.value.trim()||'';
const selectedModel=()=>$('aiModel')?.value||'';
const base=()=>$('aiEndpoint')?.value.trim().replace(/\/+$/,'')||'';
function setStatus(text,type=''){const n=$('aiStatus');if(!n)return;n.textContent=text;n.className=`ai-status ${type}`.trim();}
function addMessage(role,text,meta=''){const box=$('chatMessages');if(!box)return;const row=document.createElement('div');row.className=`ai-chat-message ${role}`;const bubble=document.createElement('div');bubble.className='ai-chat-bubble';const copy=document.createElement('div');copy.className='ai-chat-copy';copy.textContent=text;bubble.appendChild(copy);if(meta){const m=document.createElement('div');m.className='ai-chat-meta';m.textContent=meta;bubble.appendChild(m);}row.appendChild(bubble);box.appendChild(row);box.scrollTop=box.scrollHeight;return row;}
function modelsUrl(){if(provider()==='nanogpt')return'https://nano-gpt.com/api/v1/models?detailed=true';if(provider()==='openrouter')return'https://openrouter.ai/api/v1/models';const r=base();if(!r)return'';try{const u=new URL(r);let p=u.pathname.replace(/\/+$/,'').replace(/\/chat\/completions$/i,'').replace(/\/models$/i,'');u.pathname=(p+'/models').replace(/\/+/g,'/');return u.toString();}catch{return r+'/models';}}
function chatUrl(){const r=base();if(!r)return'';try{const u=new URL(r);let p=u.pathname.replace(/\/+$/,'');if(/\/chat\/completions$/i.test(p))return u.toString();p=p.replace(/\/models$/i,'');u.pathname=(p+'/chat/completions').replace(/\/+/g,'/');return u.toString();}catch{return r;}}
function headers(json=false,auth=true){const h={};if(json)h['Content-Type']='application/json';if(auth&&token())h.Authorization=`Bearer ${token()}`;if(provider()==='openrouter'){h['HTTP-Referer']=location.origin+location.pathname;h['X-Title']='Fortune Engine AI Chat';}return h;}
function startWork(kind){st.busy=true;st.started=performance.now();['sendAiBtn','testAiBtn','loadModelsBtn'].forEach(id=>{const e=$(id);if(e)e.disabled=true;});if($('chatInput'))$('chatInput').disabled=true;clearInterval(st.heartbeat);const update=()=>{const s=Math.max(0,Math.floor((performance.now()-st.started)/1000));if(kind==='test'){if($('testAiBtn'))$('testAiBtn').textContent=`⏳ Testing… ${s}s`;setStatus(`Testing ${selectedModel()||'selected model'}… ${s}s`,'working');}else if(kind==='chat'){if($('sendAiBtn'))$('sendAiBtn').textContent=`⏳ Working… ${s}s`;setStatus(`AI is working on your request… ${s}s`,'working');}else{if($('loadModelsBtn'))$('loadModelsBtn').textContent=`Loading… ${s}s`;setStatus(`Loading models… ${s}s`,'working');}};update();st.heartbeat=setInterval(update,1000);}
function stopWork(){st.busy=false;clearInterval(st.heartbeat);st.heartbeat=null;if($('sendAiBtn')){$('sendAiBtn').disabled=false;$('sendAiBtn').textContent='Send';}if($('testAiBtn')){$('testAiBtn').disabled=false;$('testAiBtn').textContent='✓ Test AI';}if($('loadModelsBtn')){$('loadModelsBtn').disabled=false;$('loadModelsBtn').textContent='↻ Load models';}if($('chatInput'))$('chatInput').disabled=false;}
async function fetchJson(url,init={},timeoutMs=120000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(url,{...init,signal:controller.signal});const text=await response.text();let data={};try{data=text?JSON.parse(text):{};}catch{throw new Error(`Provider returned non-JSON data (HTTP ${response.status}).`);}if(!response.ok)throw new Error(data?.error?.message||data?.message||`HTTP ${response.status}`);return data;}catch(e){if(e?.name==='AbortError')throw new Error(`Request timed out after ${Math.round(timeoutMs/1000)} seconds.`);if(e instanceof TypeError||/NetworkError|Failed to fetch/i.test(String(e?.message)))throw new Error(`Browser could not reach ${url}. Check CORS or endpoint.`);throw e;}finally{clearTimeout(timer);}}
function normalizeModels(data){let a=Array.isArray(data)?data:Array.isArray(data?.data)?data.data:Array.isArray(data?.models)?data.models:data?.data&&typeof data.data==='object'?Object.values(data.data):data?.models&&typeof data.models==='object'?Object.values(data.models):[];return a.map(x=>typeof x==='string'?{id:x,name:x}:x&&typeof x==='object'?{...x,id:String(x.id||x.model||x.slug||x.name||''),name:x.name||x.display_name||x.displayName||String(x.id||x.model||x.slug||x.name||'')}:null).filter(x=>x?.id&&!/embedding|rerank|tts|speech|transcri|image|video/i.test(x.id));}
function renderModels(){const select=$('aiModel');if(!select)return;const old=select.value,q=($('modelFilter')?.value||'').trim().toLowerCase();const list=st.models.filter(x=>!q||`${x.id} ${x.name||''} ${x.description||''}`.toLowerCase().includes(q));select.innerHTML='';if(!list.length){const o=document.createElement('option');o.value='';o.textContent=st.models.length?'No models match search':'Load models first';select.appendChild(o);return;}for(const x of list){const o=document.createElement('option');o.value=x.id;o.textContent=x.name&&x.name!==x.id?`${x.name} · ${x.id}`:x.id;select.appendChild(o);}if([...select.options].some(o=>o.value===old))select.value=old;}
async function loadModels(){if(st.busy)return;startWork('models');try{const url=modelsUrl();if(!/^https:\/\//i.test(url))throw new Error('Enter a valid HTTPS API base URL.');let data;if(provider()==='nanogpt'||provider()==='openrouter')data=await fetchJson(url,{method:'GET'},30000);else{try{data=await fetchJson(url,{method:'GET',headers:headers(false,true)},30000);}catch{data=await fetchJson(url,{method:'GET'},30000);}}st.models=normalizeModels(data).sort((a,b)=>String(a.name||a.id).localeCompare(String(b.name||b.id)));renderModels();setStatus(`Loaded ${st.models.length} models.`,'ok');}catch(e){setStatus(`Could not load models: ${e.message}`,'error');}finally{stopWork();}}
function extractText(data){const m=data?.choices?.[0]?.message;const c=m?.content;if(typeof c==='string'&&c.trim())return c;if(Array.isArray(c)){const t=c.map(x=>x?.text||x?.content||'').join('');if(t.trim())return t;}if(typeof m?.reasoning_content==='string'&&m.reasoning_content.trim())return m.reasoning_content;if(typeof data?.output_text==='string'&&data.output_text.trim())return data.output_text;throw new Error('Provider returned no readable assistant text.');}
async function complete(messages,maxTokens=2600,temperature=.1,timeoutMs=120000){if(!selectedModel())throw new Error('Choose a model first.');if(!token())throw new Error('Enter API token first.');const url=chatUrl();if(!/^https:\/\//i.test(url))throw new Error('Invalid chat endpoint.');const body={model:selectedModel(),messages,temperature,max_tokens:maxTokens};const data=await fetchJson(url,{method:'POST',headers:headers(true,true),body:JSON.stringify(body)},timeoutMs);return{data,text:extractText(data)};}
async function testApi(){if(st.busy)return;startWork('test');try{const t=performance.now();const r=await complete([{role:'user',content:'Reply with exactly OK and nothing else.'}],96,0,60000);const sec=((performance.now()-t)/1000).toFixed(1);setStatus(`Connected · ${r.data?.model||selectedModel()} · ${sec}s · ${r.text.trim().slice(0,60)}`,'ok');addMessage('system',`✓ API test passed in ${sec}s with ${r.data?.model||selectedModel()}.`);}catch(e){setStatus(`Test failed: ${e.message}`,'error');addMessage('system',`✕ API test failed: ${e.message}`);}finally{stopWork();}}
function wheelContext(){const c=M.loadConfig();return{groups:c.levels.map(x=>({id:x.id,name:x.name,activeAtStart:x.activeAtStart})),forfeits:c.forfeits.map(x=>({id:x.id,name:x.name,levelId:x.levelId,weight:x.weight,cooldown:x.cooldown,mystery:x.mystery,enabled:x.enabled,unlockLevels:x.unlockLevels,description:x.description})),rules:c.rules||[],spin:S?.load?.()||{}};}
function systemPrompt(){return`You edit Fortune Engine, a weighted wheel. Current wheel: ${JSON.stringify(wheelContext())}\nReturn ONLY strict JSON in this exact shape: {"reply":"short answer","actions":[],"logic":{"status":"ok|warning|error","findings":[]}}. Never return the full wheel. Use only small patch actions: add_forfeit {item}, update_forfeit {id,changes}, remove_forfeit {id}, add_group {group}, update_group {id,changes}, remove_group {id}, update_spin_style {changes}. Existing IDs must be preserved. New forfeit fields: id,name,icon,color,weight,levelId,category,description,animation,lifetime,cooldown,eventType,mystery,enabled,unlockLevels. Mystery means the real result is stored in name/icon/description but hidden on the wheel until reveal. Groups are independent unlock switches. For questions/checks use actions:[] and answer only. Change only what the user asks. Use the requested language for player-facing names/descriptions. No markdown, comments, trailing commas, or prose outside JSON.`;}
function parseJson(text){let r=String(text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'');const a=r.indexOf('{'),b=r.lastIndexOf('}');if(a>=0&&b>a)r=r.slice(a,b+1);return JSON.parse(r);}
async function structured(messages){const r=await complete(messages,3000,.1,120000);try{return parseJson(r.text);}catch(first){setStatus('AI answered, but JSON was malformed. Repairing…','working');const repair=await complete([{role:'system',content:'Return one strict valid JSON object only. Repair the malformed response. No markdown.'},{role:'user',content:r.text.slice(0,12000)}],2200,0,90000);try{return parseJson(repair.text);}catch(second){throw new Error(`AI returned invalid JSON twice. Try a non-thinking/instruct model. ${second.message}`);}}}
function uid(baseName,used){let id=slug(baseName),n=2;while(used.has(id))id=`${slug(baseName)}-${n++}`;used.add(id);return id;}
function applyActions(actions){const before=M.loadConfig(),beforeSpin=S?.load?.()||{},c=clone(before),usedF=new Set(c.forfeits.map(x=>x.id)),usedG=new Set(c.levels.map(x=>x.id));let count=0;for(const a of Array.isArray(actions)?actions:[]){if(!a||typeof a!=='object')continue;if(a.type==='add_forfeit'){const x=a.item||{},gid=x.levelId||c.levels[0]?.id;if(!c.levels.some(g=>g.id===gid))throw new Error(`Unknown group ${gid}`);c.forfeits.push({id:uid(x.id||x.name||'forfeit',usedF),name:String(x.name||'New Forfeit').slice(0,80),icon:String(x.icon||'🎯').slice(0,12),color:/^#[0-9a-f]{6}$/i.test(x.color||'')?x.color:'#65d8ff',weight:clamp(x.weight,.1,100,1),levelId:gid,category:String(x.category||'General').slice(0,40),description:String(x.description||'').slice(0,500),animation:['zoom','shake','pulse','flash','confetti'].includes(x.animation)?x.animation:'pulse',lifetime:x.lifetime&&['forever','once','spins'].includes(x.lifetime.type)?{type:x.lifetime.type,spins:Math.round(clamp(x.lifetime.spins,1,999,3))}:{type:'forever',spins:3},cooldown:Math.round(clamp(x.cooldown,0,99,0)),eventType:['normal','spinAgain','unlock','doubleSpin','immunity','randomize'].includes(x.eventType)?x.eventType:'normal',mystery:!!x.mystery,enabled:x.enabled!==false,unlockLevels:Array.isArray(x.unlockLevels)?x.unlockLevels:[]});count++;}else if(a.type==='update_forfeit'){const x=c.forfeits.find(f=>f.id===a.id||f.name===a.id);if(!x)throw new Error(`Unknown forfeit ${a.id}`);Object.assign(x,a.changes||{});count++;}else if(a.type==='remove_forfeit'){const beforeLen=c.forfeits.length;c.forfeits=c.forfeits.filter(f=>f.id!==a.id&&f.name!==a.id);if(c.forfeits.length<beforeLen)count++;}else if(a.type==='add_group'){const g=a.group||{};c.levels.push({id:uid(g.id||g.name||'group',usedG),name:String(g.name||'New Group').slice(0,60),icon:String(g.icon||'◆').slice(0,10),color:/^#[0-9a-f]{6}$/i.test(g.color||'')?g.color:'#65d8ff',activeAtStart:!!g.activeAtStart});count++;}else if(a.type==='update_group'){const g=c.levels.find(x=>x.id===a.id||x.name===a.id);if(!g)throw new Error(`Unknown group ${a.id}`);Object.assign(g,a.changes||{});count++;}else if(a.type==='remove_group'){const g=c.levels.find(x=>x.id===a.id||x.name===a.id);if(!g)throw new Error(`Unknown group ${a.id}`);if(c.forfeits.some(f=>f.levelId===g.id))throw new Error(`Group ${g.name} still contains forfeits.`);c.levels=c.levels.filter(x=>x.id!==g.id);count++;}else if(a.type==='update_spin_style'){S?.save?.({...beforeSpin,...(a.changes||{})});count++;}}
if(!c.levels.some(g=>g.activeAtStart)&&c.levels[0])c.levels[0].activeAtStart=true;const clean=M.xmlToConfig(M.configToXml(c));if(count){st.undo={config:before,spin:beforeSpin};const saved=M.saveConfig(clean);M.resetSession(saved);if($('undoAiBtn'))$('undoAiBtn').disabled=false;refreshStats();}return count;}
async function sendMessage(forced=''){if(st.busy)return;const input=$('chatInput'),text=String(forced||input?.value||'').trim();if(!text)return;if(!selectedModel()){setStatus('Choose a model first.','error');addMessage('system','Choose a model before sending a request.');return;}if(!token()){setStatus('Enter API token first.','error');addMessage('system','Enter your API token before sending a request.');return;}if(input)input.value='';addMessage('user',text);const pending=addMessage('system','⏳ AI is working on this request…','0s elapsed');st.history.push({role:'user',content:text});st.history=st.history.slice(-10);startWork('chat');const meta=pending?.querySelector('.ai-chat-meta');const timer=setInterval(()=>{if(meta)meta.textContent=`${Math.floor((performance.now()-st.started)/1000)}s elapsed`;},1000);try{const answer=await structured([{role:'system',content:systemPrompt()},...st.history]);const changed=applyActions(answer.actions||[]);pending?.remove();const reply=String(answer.reply||'Done.');addMessage('assistant',reply,changed?`Applied ${changed} change${changed===1?'':'s'}`:'No wheel changes');st.history.push({role:'assistant',content:reply});st.history=st.history.slice(-10);setStatus('Ready.','ok');}catch(e){pending?.remove();addMessage('assistant',`I could not complete that request: ${e.message}`,'Not applied');setStatus(`Request failed: ${e.message}`,'error');}finally{clearInterval(timer);stopWork();input?.focus();}}
function refreshStats(){const c=M.loadConfig();if($('chatGroupCount'))$('chatGroupCount').textContent=c.levels.length;if($('chatForfeitCount'))$('chatForfeitCount').textContent=c.forfeits.length;if($('chatRuleCount'))$('chatRuleCount').textContent=(c.rules||[]).length;}
function setPreset(){if(provider()==='nanogpt')$('aiEndpoint').value='https://nano-gpt.com/api/v1';else if(provider()==='openrouter')$('aiEndpoint').value='https://openrouter.ai/api/v1';st.models=[];renderModels();setStatus(`${provider()==='nanogpt'?'NanoGPT':provider()==='openrouter'?'OpenRouter':'Custom provider'} selected. Press Load models.`);}
function safe(label,fn){return e=>{try{return fn(e);}catch(err){console.error(label,err);setStatus(`${label} failed before network call: ${err.message}`,'error');addMessage('system',`⚠ ${label} error: ${err.message}`);}};}
function init(){window.addEventListener('error',e=>{console.error(e.error||e.message);setStatus(`JavaScript error: ${e.message}`,'error');});window.addEventListener('unhandledrejection',e=>{console.error(e.reason);setStatus(`Unexpected error: ${e.reason?.message||e.reason}`,'error');});$('aiProvider')?.addEventListener('change',safe('Provider change',setPreset));$('loadModelsBtn')?.addEventListener('click',safe('Load models',loadModels));$('modelFilter')?.addEventListener('input',safe('Model search',renderModels));$('testAiBtn')?.addEventListener('click',safe('Test AI',testApi));$('sendAiBtn')?.addEventListener('click',safe('Send message',()=>sendMessage()));$('chatInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage();}});$('toggleToken')?.addEventListener('click',()=>{const e=$('aiToken');if(!e)return;const show=e.type==='password';e.type=show?'text':'password';$('toggleToken').textContent=show?'Hide':'Show';});$('undoAiBtn')?.addEventListener('click',()=>{if(!st.undo)return;const c=M.saveConfig(st.undo.config);M.resetSession(c);S?.save?.(st.undo.spin);st.undo=null;$('undoAiBtn').disabled=true;refreshStats();addMessage('system','Last AI edit undone.');});$('clearChatBtn')?.addEventListener('click',()=>{st.history=[];$('chatMessages').innerHTML='';addMessage('system','Chat cleared.');});document.querySelectorAll('[data-ai-command]').forEach(b=>b.addEventListener('click',()=>sendMessage(b.dataset.aiCommand||'')));refreshStats();renderModels();addMessage('system','Ready. Every AI request will now show a live elapsed-time indicator while it is running.');setStatus('Ready.','ok');window.FortuneAiDebug={loadModels,testApi,sendMessage,get model(){return selectedModel();},get provider(){return provider();},get chatUrl(){return chatUrl();}};}
init();
})();