(()=>{'use strict';
const M=window.FortuneModel,S=window.FortuneSpinStyle,$=id=>document.getElementById(id);if(!M)return;
const st={models:[],msgs:[],busy:false,undo:null};const clone=v=>M.deepClone?M.deepClone(v):JSON.parse(JSON.stringify(v));
const status=(t,c='')=>{const n=$('aiStatus');if(n){n.textContent=t;n.className=`ai-status ${c}`.trim();}};
const msg=(r,t,m='')=>{const b=$('chatMessages');if(!b)return;const row=document.createElement('div');row.className=`ai-chat-message ${r}`;const q=document.createElement('div');q.className='ai-chat-bubble';const x=document.createElement('div');x.className='ai-chat-copy';x.textContent=t;q.appendChild(x);if(m){const z=document.createElement('div');z.className='ai-chat-meta';z.textContent=m;q.appendChild(z);}row.appendChild(q);b.appendChild(row);b.scrollTop=b.scrollHeight;};
const provider=()=>$('aiProvider')?.value||'custom', token=()=>$('aiToken')?.value.trim()||'', model=()=>$('aiModel')?.value||'', base=()=>$('aiEndpoint')?.value.trim().replace(/\/+$/,'')||'';
function chatUrl(){let r=base();if(!r)return'';try{const u=new URL(r);let p=u.pathname.replace(/\/+$/,'');if(/\/chat\/completions$/i.test(p))return u.toString();if(/\/models$/i.test(p))p=p.replace(/\/models$/i,'');u.pathname=(p+'/chat/completions').replace(/\/+/g,'/');return u.toString();}catch{return r;}}
function modelsUrl(){if(provider()==='nanogpt')return'https://nano-gpt.com/api/v1/models?detailed=true';if(provider()==='openrouter')return'https://openrouter.ai/api/v1/models';let r=base();if(!r)return'';try{const u=new URL(r);let p=u.pathname.replace(/\/+$/,'').replace(/\/chat\/completions$/i,'').replace(/\/models$/i,'');u.pathname=(p+'/models').replace(/\/+/g,'/');return u.toString();}catch{return r+'/models';}}
function headers(json=false,auth=true){const h={};if(json)h['Content-Type']='application/json';if(auth&&token())h.Authorization=`Bearer ${token()}`;if(provider()==='openrouter'){h['HTTP-Referer']=location.origin+location.pathname;h['X-Title']='Fortune Engine AI Chat';}return h;}
async function getJson(url,init={}){try{const r=await fetch(url,init),txt=await r.text();let d={};try{d=txt?JSON.parse(txt):{};}catch{throw new Error(`Non-JSON response (HTTP ${r.status})`);}if(!r.ok)throw new Error(d?.error?.message||d?.message||`HTTP ${r.status}`);return d;}catch(e){if(e instanceof TypeError||/NetworkError|Failed to fetch/i.test(String(e.message)))throw new Error(`Browser could not reach ${url}. Check CORS/endpoint.`);throw e;}}
function normalizeModels(d){let a=Array.isArray(d)?d:Array.isArray(d?.data)?d.data:Array.isArray(d?.models)?d.models:d?.data&&typeof d.data==='object'?Object.values(d.data):d?.models&&typeof d.models==='object'?Object.values(d.models):[];return a.map(x=>typeof x==='string'?{id:x,name:x}:x&&typeof x==='object'?{...x,id:String(x.id||x.model||x.slug||x.name||''),name:x.name||x.display_name||x.displayName||String(x.id||x.model||x.slug||'')}:null).filter(x=>x?.id&&!/embedding|rerank|tts|speech|transcri|image|video/i.test(x.id));}
function renderModels(){const s=$('aiModel');if(!s)return;const old=s.value,q=($('modelFilter')?.value||'').toLowerCase();const a=st.models.filter(x=>!q||`${x.id} ${x.name||''} ${x.description||''}`.toLowerCase().includes(q));s.innerHTML='';if(!a.length){const o=document.createElement('option');o.value='';o.textContent=st.models.length?'No models match search':'Load models first';s.appendChild(o);return;}a.forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.name&&x.name!==x.id?`${x.name} · ${x.id}`:x.id;s.appendChild(o);});if([...s.options].some(o=>o.value===old))s.value=old;}
async function loadModels(){const b=$('loadModelsBtn');if(!b||st.busy)return;const u=modelsUrl();if(!/^https:\/\//i.test(u))return status('Enter a valid HTTPS API base URL.','error');b.disabled=true;b.textContent='Loading…';status('Loading models…','working');try{let d;if(provider()==='nanogpt'||provider()==='openrouter')d=await getJson(u,{method:'GET'});else{try{d=await getJson(u,{method:'GET',headers:headers(false,true)});}catch(e){d=await getJson(u,{method:'GET'});}}st.models=normalizeModels(d).sort((a,b)=>String(a.name||a.id).localeCompare(String(b.name||b.id)));renderModels();status(`Loaded ${st.models.length} models.`,'ok');}catch(e){status(`Could not load models: ${e.message}`,'error');}finally{b.disabled=false;b.textContent='↻ Load models';}}
function extract(d){const c=d?.choices?.[0]?.message?.content;if(typeof c==='string')return c;if(Array.isArray(c))return c.map(x=>x?.text||x?.content||'').join('');if(typeof d?.output_text==='string')return d.output_text;throw new Error('No readable AI response.');}
async function complete(messages,max=2500,temp=.1){if(!model())throw new Error('Choose a model first.');if(!token())throw new Error('Enter API token first.');const u=chatUrl();if(!/^https:\/\//i.test(u))throw new Error('Invalid chat endpoint.');const d=await getJson(u,{method:'POST',headers:headers(true,true),body:JSON.stringify({model:model(),messages,temperature:temp,max_tokens:max})});return{data:d,text:extract(d)};}
async function test(){const b=$('testAiBtn');if(!b||st.busy)return;b.disabled=true;b.textContent='Testing…';status('Testing selected model…','working');const t=performance.now();try{const r=await complete([{role:'user',content:'Reply exactly OK'}],24,0);status(`Connected · ${r.data?.model||model()} · ${((performance.now()-t)/1000).toFixed(1)}s · ${r.text.trim().slice(0,20)}`,'ok');msg('system',`Connection test passed for ${r.data?.model||model()}.`);}catch(e){status(`Test failed: ${e.message}`,'error');}finally{b.disabled=false;b.textContent='✓ Test AI';}}
function context(){const c=M.loadConfig();return{groups:c.levels.map(x=>({id:x.id,name:x.name})),forfeits:c.forfeits.map(x=>({id:x.id,name:x.name,levelId:x.levelId,weight:x.weight,cooldown:x.cooldown,mystery:x.mystery,enabled:x.enabled,unlockLevels:x.unlockLevels,description:x.description})),rules:c.rules,spin:S?.load?.()||{}};}
function sys(){return`You edit a weighted wheel configuration by returning SMALL PATCH ACTIONS only. Current wheel: ${JSON.stringify(context())}\nReturn ONLY strict JSON: {"reply":"text","actions":[],"logic":{"status":"ok|warning|error","findings":[]}}. Actions: add_forfeit {item}, update_forfeit {id,changes}, remove_forfeit {id}, add_group {group}, update_group {id,changes}, remove_group {id}, update_spin_style {changes}. Existing ids must be preserved. New forfeit fields may include id,name,icon,color,weight,levelId,category,description,animation,lifetime,cooldown,eventType,mystery,enabled,unlockLevels. Mystery stores the real hidden result and only hides display. Groups are independent unlock switches. For a check/question use actions:[] and answer only. Change only what was requested. Use requested language for names/descriptions.`;}
function parse(t){let r=String(t||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'');const a=r.indexOf('{'),b=r.lastIndexOf('}');if(a>=0&&b>a)r=r.slice(a,b+1);return JSON.parse(r);}
async function structured(messages){const r=await complete(messages,2600,.1);try{return parse(r.text);}catch(e){status('Malformed JSON returned. Repairing automatically…','working');const q=await complete([{role:'system',content:'Repair this into one strict valid JSON object only. No markdown.'},{role:'user',content:r.text.slice(0,12000)}],1800,0);try{return parse(q.text);}catch{throw new Error(`Model returned invalid JSON twice: ${e.message}`);}}}
const clamp=(v,a,b,d)=>{v=Number(v);return Number.isFinite(v)?Math.min(b,Math.max(a,v)):d;};const slug=s=>String(s||'item').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'item';
function uid(base,used){let i=slug(base),n=2;while(used.has(i))i=`${slug(base)}-${n++}`;used.add(i);return i;}
function apply(actions){const before=M.loadConfig(),beforeSpin=S?.load?.()||{},c=clone(before),used=new Set(c.forfeits.map(x=>x.id)),usedG=new Set(c.levels.map(x=>x.id));let n=0;for(const a of Array.isArray(actions)?actions:[]){if(a.type==='add_forfeit'){const x=a.item||{},gid=x.levelId||c.levels[0]?.id;if(!c.levels.some(g=>g.id===gid))throw new Error(`Unknown group ${gid}`);c.forfeits.push({id:uid(x.id||x.name||'forfeit',used),name:String(x.name||'New Forfeit'),icon:String(x.icon||'🎯'),color:/^#[0-9a-f]{6}$/i.test(x.color||'')?x.color:'#65d8ff',weight:clamp(x.weight,.1,100,1),levelId:gid,category:String(x.category||'General'),description:String(x.description||''),animation:['zoom','shake','pulse','flash','confetti'].includes(x.animation)?x.animation:'pulse',lifetime:x.lifetime&&['forever','once','spins'].includes(x.lifetime.type)?x.lifetime:{type:'forever',spins:3},cooldown:Math.round(clamp(x.cooldown,0,99,0)),eventType:['normal','spinAgain','unlock','doubleSpin','immunity','randomize'].includes(x.eventType)?x.eventType:'normal',mystery:!!x.mystery,enabled:x.enabled!==false,unlockLevels:Array.isArray(x.unlockLevels)?x.unlockLevels:[]});n++;}
else if(a.type==='update_forfeit'){const x=c.forfeits.find(f=>f.id===a.id||f.name===a.id);if(!x)throw new Error(`Unknown forfeit ${a.id}`);Object.assign(x,a.changes||{});n++;}
else if(a.type==='remove_forfeit'){const l=c.forfeits.length;c.forfeits=c.forfeits.filter(f=>f.id!==a.id&&f.name!==a.id);if(c.forfeits.length<l)n++;}
else if(a.type==='add_group'){const g=a.group||{};c.levels.push({id:uid(g.id||g.name||'group',usedG),name:String(g.name||'New Group'),icon:String(g.icon||'◆'),color:/^#[0-9a-f]{6}$/i.test(g.color||'')?g.color:'#65d8ff',activeAtStart:!!g.activeAtStart});n++;}
else if(a.type==='update_group'){const g=c.levels.find(x=>x.id===a.id||x.name===a.id);if(!g)throw new Error(`Unknown group ${a.id}`);Object.assign(g,a.changes||{});n++;}
else if(a.type==='remove_group'){if(c.forfeits.some(f=>f.levelId===a.id))throw new Error(`Group ${a.id} still contains forfeits.`);const l=c.levels.length;c.levels=c.levels.filter(g=>g.id!==a.id&&g.name!==a.id);if(c.levels.length<l)n++;}
else if(a.type==='update_spin_style'){S?.save?.({...beforeSpin,...(a.changes||{})});n++;}}
if(!c.levels.some(g=>g.activeAtStart)&&c.levels[0])c.levels[0].activeAtStart=true;const clean=M.xmlToConfig(M.configToXml(c));if(n){st.undo={config:before,spin:beforeSpin};const saved=M.saveConfig(clean);M.resetSession(saved);$('undoAiBtn').disabled=false;stats();}return n;}
function busy(v){st.busy=v;['sendAiBtn','testAiBtn','loadModelsBtn'].forEach(id=>{const e=$(id);if(e)e.disabled=v;});if($('chatInput'))$('chatInput').disabled=v;}
async function send(force=''){if(st.busy)return;const i=$('chatInput'),t=String(force||i?.value||'').trim();if(!t)return;if(i)i.value='';msg('user',t);st.msgs.push({role:'user',content:t});st.msgs=st.msgs.slice(-8);busy(true);status('AI is reading the current wheel…','working');try{const a=await structured([{role:'system',content:sys()},...st.msgs]);const k=apply(a.actions||[]),r=String(a.reply||'Done.');msg('assistant',r,k?`Applied ${k} change${k===1?'':'s'}`:'No wheel changes');st.msgs.push({role:'assistant',content:r});status('Ready.','ok');}catch(e){msg('assistant',`I could not complete that request: ${e.message}`,'Not applied');status(e.message,'error');}finally{busy(false);i?.focus();}}
function stats(){const c=M.loadConfig();$('chatGroupCount').textContent=c.levels.length;$('chatForfeitCount').textContent=c.forfeits.length;$('chatRuleCount').textContent=(c.rules||[]).length;}
function preset(){if(provider()==='nanogpt')$('aiEndpoint').value='https://nano-gpt.com/api/v1';else if(provider()==='openrouter')$('aiEndpoint').value='https://openrouter.ai/api/v1';st.models=[];renderModels();status(`${provider()==='nanogpt'?'NanoGPT':provider()==='openrouter'?'OpenRouter':'Custom provider'} selected. Press Load models.`);}
function init(){const p=$('aiProvider');if(p&&!p.querySelector('option[value="nanogpt"]')){const o=document.createElement('option');o.value='nanogpt';o.textContent='NanoGPT';p.insertBefore(o,p.querySelector('option[value="custom"]'));}p?.addEventListener('change',preset);$('loadModelsBtn')?.addEventListener('click',loadModels);$('modelFilter')?.addEventListener('input',renderModels);$('testAiBtn')?.addEventListener('click',test);$('sendAiBtn')?.addEventListener('click',()=>send());$('chatInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}});$('toggleToken')?.addEventListener('click',()=>{const e=$('aiToken'),show=e.type==='password';e.type=show?'text':'password';$('toggleToken').textContent=show?'Hide':'Show';});$('undoAiBtn')?.addEventListener('click',()=>{if(!st.undo)return;const c=M.saveConfig(st.undo.config);M.resetSession(c);S?.save?.(st.undo.spin);st.undo=null;$('undoAiBtn').disabled=true;stats();msg('system','Last AI edit undone.');});$('clearChatBtn')?.addEventListener('click',()=>{st.msgs=[];$('chatMessages').innerHTML='';msg('system','Chat cleared.');});document.querySelectorAll('[data-ai-command]').forEach(b=>b.addEventListener('click',()=>send(b.dataset.aiCommand||'')));stats();renderModels();msg('system','Ready. Load models, choose one, test the connection, then tell me what to add, remove, change, or check.');}
init();})();
