(() => {
'use strict';
const M=window.FortuneModel,$=id=>document.getElementById(id);
let config=M.loadConfig(),session=M.loadSession(config),spinning=false,rotation=0,audio=null,segments=[];
const rotor=$('wheelRotor'),spinBtn=$('spinBtn'),pointer=$('pointer'),overlay=$('resultOverlay'),card=$('resultCard'),mystery=$('resultMystery'),rIcon=$('resultIcon'),rTitle=$('resultTitle'),rDesc=$('resultDescription'),rCategory=$('resultCategory'),unlockNotice=$('unlockNotice'),fileInput=$('fileInput');
const norm=d=>((d%360)+360)%360;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const polar=(cx,cy,r,a)=>({x:cx+r*Math.cos(a*Math.PI/180),y:cy+r*Math.sin(a*Math.PI/180)});
function arc(cx,cy,r,a,b){const p=polar(cx,cy,r,a),q=polar(cx,cy,r,b);return `M ${cx} ${cy} L ${p.x} ${p.y} A ${r} ${r} 0 ${b-a>180?1:0} 1 ${q.x} ${q.y} Z`;}
function weight(i){return Math.max(.01,i.weight*(Number(session.runtime[i.id]?.weightMultiplier)||1));}
function active(){return config.forfeits.filter(i=>{const r=session.runtime[i.id];return i.enabled&&r&&!r.removed&&r.cooldown<=0&&session.activeLevels[i.levelId]&&!(i.lifetime.type==='spins'&&r.remainingSpins!==null&&r.remainingSpins<=0);});}
function makeSegments(items){const total=items.reduce((s,i)=>s+weight(i),0);let a=-90;return items.map(item=>{const w=weight(item),span=total?w/total*360:0,o={item,start:a,end:a+span,span,weight:w,total};a+=span;return o;});}
function svg(tag,attrs={}){const n=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));return n;}
function renderWheel(){
 const items=active();segments=makeSegments(items);rotor.innerHTML='';spinBtn.disabled=spinning||!segments.length;
 if(!segments.length){rotor.innerHTML='<div class="wheel-empty"><strong>No active forfeits</strong><span>Unlock a group or add entries in Edit.</span></div>';return;}
 const s=svg('svg',{viewBox:'0 0 600 600',role:'img','aria-label':`${segments.length} active wheel entries`});s.classList.add('wheel-svg');
 segments.forEach((g,idx)=>{
  const p=svg('path',{d:arc(300,300,286,g.start,g.end),fill:g.item.color,class:'wheel-segment','data-index':idx});const t=svg('title');t.textContent=`${g.item.name} · ${(g.weight/g.total*100).toFixed(1)}%`;p.appendChild(t);s.appendChild(p);
  const edge=polar(300,300,286,g.start);s.appendChild(svg('line',{x1:300,y1:300,x2:edge.x,y2:edge.y,class:'wheel-divider'}));
  if(g.span>=7){const mid=g.start+g.span/2,pos=polar(300,300,g.span<18?230:205,mid),grp=svg('g',{transform:`translate(${pos.x} ${pos.y}) rotate(${mid+90})`}),ic=svg('text',{x:0,y:config.settings.showTextOnWheel&&g.span>=20?-5:7,'text-anchor':'middle',class:'wheel-icon'});ic.textContent=g.item.mystery?'❓':g.item.icon;grp.appendChild(ic);
   if(config.settings.showTextOnWheel&&g.span>=20){const tx=svg('text',{x:0,y:25,'text-anchor':'middle',class:'wheel-label'});let n=g.item.mystery?'MYSTERY':g.item.name,lim=g.span>=35?16:10;tx.textContent=n.length>lim?n.slice(0,lim-1)+'…':n;grp.appendChild(tx);}s.appendChild(grp);}
 });s.appendChild(svg('circle',{cx:300,cy:300,r:286,class:'wheel-rim'}));rotor.appendChild(s);rotor.style.transform=`rotate(${rotation}deg)`;
}
function renderLevels(){const box=$('levelLights');box.innerHTML='';config.levels.forEach(l=>{const on=!!session.activeLevels[l.id],d=document.createElement('div');d.className=`level-light ${on?'active':'locked'}`;d.style.setProperty('--level-color',l.color);d.innerHTML=`<span class="level-dot">${esc(l.icon)}</span><span>${esc(l.name)}</span><b>${on?'ON':'LOCKED'}</b>`;box.appendChild(d);});}
function renderOdds(){const c=document.querySelector('.probability-card');if(c)c.hidden=!config.settings.showProbabilities;const box=$('probabilityList');box.innerHTML='';const list=active(),total=list.reduce((s,i)=>s+weight(i),0);list.sort((a,b)=>weight(b)-weight(a)).forEach(i=>{const d=document.createElement('div');d.className='probability-row';d.innerHTML=`<span class="prob-icon" style="--item-color:${i.color}">${esc(i.mystery?'❓':i.icon)}</span><span class="prob-name"><strong>${esc(i.mystery?'Mystery':i.name)}</strong><small>weight ${weight(i).toFixed(1)}</small></span><span class="prob-value">${(weight(i)/total*100).toFixed(1)}%</span>`;box.appendChild(d);});if(!list.length)box.innerHTML='<div class="empty-small">No selectable entries.</div>';}
function renderHistory(){const box=$('historyList'),h=session.history.slice(-8).reverse();box.innerHTML='';$('historyHint').textContent=session.history.length?`${session.history.length} result${session.history.length===1?'':'s'} this session`:'Nothing selected yet';h.forEach((e,i)=>{const d=document.createElement('div');d.className='history-item';d.innerHTML=`<span class="history-index">${session.history.length-i}</span><span class="history-icon" style="--item-color:${e.color}">${esc(e.icon)}</span><span class="history-copy"><strong>${esc(e.name)}</strong><small>${esc(e.category)}${e.unlocked?.length?' · unlocked '+esc(e.unlocked.join(', ')):''}</small></span><span class="history-time">${esc(e.time)}</span>`;box.appendChild(d);});if(!h.length)box.innerHTML='<div class="history-empty">Your last results will appear here.</div>';$('undoBtn').disabled=!session.undoStack.length||spinning;}
function renderAll(){document.title=`${config.settings.title} · Fortune Engine`;renderLevels();renderWheel();renderOdds();renderHistory();$('spinCount').textContent=session.spinCount;$('activeCount').textContent=active().length;$('chanceHint').textContent=active().length?'WEIGHTED':'—';M.saveSession(session);}
function choose(list){let n=Math.random()*list.reduce((s,g)=>s+g.weight,0);for(const g of list){n-=g.weight;if(n<=0)return g;}return list.at(-1);}
function pointerIndex(r,list){const a=norm(-90-r);for(let i=0;i<list.length;i++)if(norm(a-norm(list[i].start))<=list[i].span+.0001)return i;return 0;}
const ease=t=>1-Math.pow(1-t,5);
function snapshot(){const s=M.deepClone(session);s.undoStack=[];session.undoStack.push(s);if(session.undoStack.length>12)session.undoStack.shift();}
async function spin(){
 if(spinning||!segments.length)return;hideResult();spinning=true;spinBtn.disabled=true;$('undoBtn').disabled=true;state('Spinning…','The wheel is deciding. Cooldowns and unlocks are applied only after it stops.');snapshot();
 const list=makeSegments(active()),pick=choose(list),target=pick.start+pick.span*(.22+Math.random()*.56),desired=norm(-90-target),extra=norm(desired-norm(rotation)),final=rotation+(config.settings.minTurns+Math.floor(Math.random()*3))*360+extra,min=Math.min(config.settings.minSpinSeconds,config.settings.maxSpinSeconds),max=Math.max(config.settings.minSpinSeconds,config.settings.maxSpinSeconds),duration=(min+Math.random()*(max-min))*1000,start=rotation,delta=final-start,t0=performance.now();let last=pointerIndex(start,list);
 await new Promise(done=>{const frame=now=>{const t=Math.min(1,(now-t0)/duration);rotation=start+delta*ease(t);rotor.style.transform=`rotate(${rotation}deg)`;const idx=pointerIndex(rotation,list);if(idx!==last){last=idx;tick();}t<1?requestAnimationFrame(frame):done();};requestAnimationFrame(frame);});
 rotation=final;rotor.style.transform=`rotate(${rotation}deg)`;const outcome=applyResult(pick.item);spinning=false;renderAll();showResult(pick.item,outcome);
}
function evaluateRules(current){const done=new Set(session.history.map(h=>h.id));done.add(current);const unlocked=[],rules=[];(config.rules||[]).forEach(r=>{if(!r.enabled||!r.conditionForfeitIds.length)return;const m=r.conditionForfeitIds.map(id=>done.has(id)),ok=r.mode==='any'?m.some(Boolean):m.every(Boolean);if(!ok)return;const fresh=[];r.unlockLevels.forEach(id=>{if(session.activeLevels[id])return;session.activeLevels[id]=true;const l=config.levels.find(x=>x.id===id);if(l){unlocked.push(l.name);fresh.push(l.name);}});if(fresh.length)rules.push(r.name);});return{unlocked,rules};}
function applyResult(item){
 const before={...session.activeLevels},unlocked=[];session.spinCount++;Object.values(session.runtime).forEach(r=>{if(r.cooldown>0)r.cooldown--;});
 item.unlockLevels.forEach(id=>{if(!session.activeLevels[id]){session.activeLevels[id]=true;const l=config.levels.find(x=>x.id===id);if(l)unlocked.push(l.name);}});evaluateRules(item.id).unlocked.forEach(n=>{if(!unlocked.includes(n))unlocked.push(n);});
 config.forfeits.forEach(i=>{const r=session.runtime[i.id];if(!r||!before[i.levelId]||r.removed)return;if(i.lifetime.type==='spins'&&r.remainingSpins!==null){r.remainingSpins--;if(r.remainingSpins<=0)r.removed=true;}});
 const rt=session.runtime[item.id];if(item.lifetime.type==='once')rt.removed=true;if(!rt.removed&&item.cooldown>0)rt.cooldown=item.cooldown;
 let msg='';if(item.eventType==='spinAgain')msg='Spin again is active — the next spin is waiting for you.';else if(item.eventType==='doubleSpin'){session.doubleSpinTokens=(session.doubleSpinTokens||0)+1;msg='Double-spin token earned.';}else if(item.eventType==='immunity'){session.immunityTokens=(session.immunityTokens||0)+1;msg=`Immunity token earned. You now have ${session.immunityTokens}.`;}else if(item.eventType==='randomize'){active().forEach(i=>session.runtime[i.id].weightMultiplier=Number((.6+Math.random()).toFixed(2)));msg='Chaos Shuffle changed the effective weights of active entries.';}else if(item.eventType==='unlock'&&unlocked.length)msg=`${unlocked.join(', ')} ${unlocked.length===1?'is':'are'} now active.`;
 session.history.push({id:item.id,name:item.name,icon:item.icon,color:item.color,category:item.category,unlocked,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})});if(session.history.length>50)session.history.shift();M.saveSession(session);return{unlocked,specialMessage:msg};
}
function state(t,x){$('stateTitle').textContent=t;$('stateText').textContent=x;}
function showResult(item,o){overlay.hidden=false;overlay.classList.add('show');card.className=`result-card result-${item.animation}`;card.style.setProperty('--result-color',item.color);rCategory.textContent=item.category||'RESULT';rTitle.textContent=item.mystery?'Mystery revealed…':item.name;rDesc.textContent=item.mystery?'The wheel kept this one hidden.':(item.description||'Selected by the wheel.');rIcon.textContent=item.mystery?'❓':item.icon;mystery.hidden=!item.mystery;rIcon.hidden=item.mystery;unlockNotice.hidden=!(o.unlocked.length||o.specialMessage);unlockNotice.textContent=o.unlocked.length?`UNLOCKED · ${o.unlocked.join(' + ')}`:o.specialMessage;$('resultSpinBtn').textContent=item.eventType==='spinAgain'?'Spin again!':'Spin again';tone();
 if(item.mystery)setTimeout(()=>{if(overlay.hidden)return;mystery.hidden=true;rIcon.hidden=false;rIcon.textContent=item.icon;rTitle.textContent=item.name;rDesc.textContent=item.description||'Mystery revealed.';card.classList.add('mystery-revealed');if(item.animation==='confetti')confetti();},950);else if(item.animation==='confetti')setTimeout(confetti,180);
 const bits=[item.name];if(o.unlocked.length)bits.push('Unlocked '+o.unlocked.join(', '));if(o.specialMessage)bits.push(o.specialMessage);state('Last result',bits.join(' · '));}
function hideResult(){overlay.classList.remove('show');overlay.hidden=true;card.className='result-card';}
function confetti(){const colors=['#fff','#57d3ff','#ff6bd6','#ffb454','#8b7cff'];for(let i=0;i<38;i++){const p=document.createElement('i');p.className='confetti-piece';p.style.setProperty('--x',`${(Math.random()-.5)*520}px`);p.style.setProperty('--y',`${-80-Math.random()*330}px`);p.style.setProperty('--r',`${Math.random()*720-360}deg`);p.style.setProperty('--c',colors[i%colors.length]);card.appendChild(p);setTimeout(()=>p.remove(),1600);}}
function ctx(){if(!config.settings.soundEnabled)return null;if(!audio){const C=window.AudioContext||window.webkitAudioContext;if(C)audio=new C();}if(audio?.state==='suspended')audio.resume().catch(()=>{});return audio;}
function beep(freq=.0,d=.04,g=.04,delay=0){const c=ctx();if(!c)return;const o=c.createOscillator(),v=c.createGain(),at=c.currentTime+delay;o.frequency.value=freq;v.gain.setValueAtTime(g,at);v.gain.exponentialRampToValueAtTime(.001,at+d);o.connect(v).connect(c.destination);o.start(at);o.stop(at+d+.01);}
function tick(){pointer.classList.remove('tick');void pointer.offsetWidth;pointer.classList.add('tick');beep(780,.035,.045);}
function tone(){[440,660,880].forEach((f,i)=>beep(f,.16,.055,i*.08));}
function undo(){if(spinning||!session.undoStack.length)return;const stack=session.undoStack,prev=stack.pop();session={...prev,undoStack:stack};rotation=0;state('Last spin undone','The previous wheel state, cooldowns, lifetimes and unlocks have been restored.');renderAll();toast('Last spin restored.');}
function reset(){if(!confirm('Reset the current session? This clears spin history, cooldowns and unlocked groups. Your wheel configuration stays intact.'))return;session=M.resetSession(config);rotation=0;state('Session reset','The wheel is back to its configured starting groups.');renderAll();toast('Session reset.');}
function toast(m){const n=$('toast');n.textContent=m;n.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove('show'),2400);}
async function loadXml(file){try{config=M.saveConfig(await M.readXmlFile(file));session=M.resetSession(config);rotation=0;renderAll();state('XML loaded','A fresh session was started with the imported wheel configuration.');toast('Wheel loaded from XML.');}catch(e){toast(e.message||'Could not load XML.');}finally{fileInput.value='';}}
spinBtn.addEventListener('click',()=>{ctx();spin();});$('saveBtn').addEventListener('click',()=>M.downloadXml(config));$('loadBtn').addEventListener('click',()=>fileInput.click());fileInput.addEventListener('change',()=>loadXml(fileInput.files?.[0]));$('undoBtn').addEventListener('click',undo);$('resetBtn').addEventListener('click',reset);$('resultCloseBtn').addEventListener('click',hideResult);$('resultSpinBtn').addEventListener('click',()=>{hideResult();setTimeout(spin,100);});overlay.addEventListener('click',e=>{if(e.target.classList.contains('result-backdrop'))hideResult();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!overlay.hidden)hideResult();});renderAll();
})();
